# LabelEncoder

def encode(value, x):
    return {
        'F': lambda x: 0,
        'M': lambda x: 1,
        'East Anglian Region': lambda x: 0,
        'East Midlands Region': lambda x: 1,
        'Ireland': lambda x: 2,
        'London Region': lambda x: 3,
        'North Region': lambda x: 4,
        'North Western Region': lambda x: 5,
        'Scotland': lambda x: 6,
        'South East Region': lambda x: 7,
        'South Region': lambda x: 8,
        'South West Region': lambda x: 9,
        'Wales': lambda x: 10,
        'West Midlands Region': lambda x: 11,
        'Yorkshire Region': lambda x: 12,
        'A Level or Equivalent': lambda x: 0,
        'No Formal Qualification': lambda x: 1,
        'Higher Education Qualification': lambda x: 2,
        'Post Graduation Qualification': lambda x: 3,
        'A Level or Equivalent': lambda x: 4,
        '0-10%': lambda x: 0,
        '10%-20%': lambda x: 1,
        '20%-30%': lambda x: 2,
        '30%-40%': lambda x: 3,
        '40%-50%': lambda x: 4,
        '50%-60%': lambda x: 5,
        '60%-70%': lambda x: 6,
        '70%-80%': lambda x: 7,
        '80%-90%': lambda x: 8,
        '90%-100%': lambda x: 9,
        '0-35': lambda x: 0,
        '35-55': lambda x: 1,
        '55<=': lambda x: 2,
        '0': lambda x: 0,
        '1': lambda x: 1,
        '2': lambda x: 2,
        '3': lambda x: 3,
        '4': lambda x: 4,
        '5': lambda x: 5,
        '6': lambda x: 6,
        'AAA': lambda x: 0,
        'BBB': lambda x: 1,
        'DDD': lambda x: 2,
        'FFF': lambda x: 3,
        'GGG': lambda x: 4,
        'CCC': lambda x: 5,
        'EEE': lambda x: 6,
        '2013B': lambda x: 0,
        '2013J': lambda x: 1,
        '2014B': lambda x: 2,
        '2014J': lambda x: 3,
    }.get(value)(x)